# Copyright (c) 2025, NVIDIA CORPORATION.
# SPDX-FileCopyrightText: Copyright (c) 2026 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: BSD-3-Clause AND MIT

[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=64.0.0",
]

[project]
name = "amd-distributed-hipucxx"
dynamic = ["version"]
description = "UCX w/ ROCm communication module for Dask Distributed"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "Advanced Micro Devices, Inc." },
    { name = "NVIDIA Corporation" },
]
license = { text = "BSD-3-Clause" }
requires-python = ">=3.10"
dependencies = [
    "numba-hip",
    "pyyaml>=6",
    "amd-hipucxx==0.1.*",
]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.entry-points."distributed.comm.backends"]
ucx = "distributed_ucxx:UCXXBackend"
ucxx = "distributed_ucxx:UCXXBackendLegacyPrefix"

[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinx-click>=2.7.1",
    "sphinx-rtd-theme>=0.5.1",
]
test = [
    "amd-hipdf",
    "amd-cupy",
    "numpy>=1.23,<3.0a0",
    "pytest",
    "pytest-rerunfailures!=16.0.0",
]

[project.urls]
Homepage = "https://github.com/ROCm-DS/hip-ucxx"

[tool.coverage.run]
disable_warnings = [
    "include-ignored",
]
include = [
    "distributed_ucxx/*",
]
omit = [
    "distributed_ucxx/tests/*",
]

[tool.setuptools.packages.find]
exclude = [
    "docs",
    "tests",
    "docs.*",
    "tests.*",
]

[tool.setuptools.package-data]
"distributed_ucxx" = ["VERSION", "*.yaml"]

[tool.setuptools.dynamic]
version = {file = "distributed_ucxx/VERSION"}

[tool.pydistcheck]
select = [
    "distro-too-large-compressed",
]

# PyPI limit is 100 MiB, fail CI before we get too close to that
max_allowed_size_compressed = '75M'

[tool.pytest.ini_options]
markers = [
    "ignore_alive_references",
    "gpu",
    "slow",
]
